### ISSUE TITLE
Missing PyPI distribution

### ISSUE THREAD

**Issue by hackebrot** [ajdavis/lektor-tags#1]
Hi @ajdavis! :wave: 

I stumbled upon this repo when looking for existing solutions to tags in lektor.

Following the setup guide, I realized there is no package at https://pypi.python.org/pypi/lektor-tags/

Mind to cut a release?

Cheers
Raphael

**Comment by ajdavis** [comment]
I'm waiting for Lektor 2.0 to be released before I push this to PyPI.

**Comment by hackebrot** [comment]
Okay, fair enough.

**Comment by ajdavis** [comment]
Specifically, this plugin relies on two features that are in Lektor's master branch but not released:

- Added support for virtual paths and made pagination work with it.
- Added support for Query.distinct

... to avoid disappointment, I'm not publishing to PyPI until the published version of Lektor works with it.

**Comment by hackebrot** [comment]
Appreciate the feedback! :bow: 

Just to let you know. I've had this disappointment when searching GitHub for **lektor tags** and tried to run ``lektor plugins add lektor-tags``. Lektor won't exit gracefully as the package is registered on PyPI but you can't download and install a distribution.

I think a note on this readme will help others who encounter the same.

**Comment by zejn** [comment]
Just as a note, Lektor 2.0 has now been released.

**Comment by ajdavis** [comment]
Published, thanks for reminding me: https://pypi.python.org/pypi
